apiVersion: v1
kind: ServiceAccount
metadata:
  name: scalyr-service-account
  namespace: default
secrets:
- name: scalyr-api-key
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scalyr-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods","namespaces","replicationcontrollers"]
  verbs: ["get","list"]
- apiGroups: ["apps"]
  resources: ["daemonsets","deployments","replicasets","statefulsets","namespaces"]
  verbs: ["get","list"]
- apiGroups: ["batch", "extensions"]
  resources: ["cronjobs","jobs"]
  verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scalyr-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scalyr-clusterrole
subjects:
  - kind: ServiceAccount
    name: scalyr-service-account
    namespace: default
