configMapGenerator:
  - name: codespeed-config-agent-settings
    namespace: agent-benchmark
    files:
      - agent-config.json
    literals:
      - codespeed_executable=2.7.17-Kub-idle-conf5s
      - LOG_WRITER_ADDITIONAL_ARGS=
