name: Build agent packages.

on: [push]

env:
  DOCKER_BUILDKIT: 1


jobs:
  # TODO move here tests from the CicleCi.
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-type: [docker-json]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install python.
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.10

      - name: Perform the deployment of the test environment.
        uses: ./.github/actions/perform-deployment
        with:
          deployment-name: "test_environment"

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Run image test.
        env:
            SCALYR_API_KEY: ${{ secrets.SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN }}
        run: |
          python3 tests/package_tests/run_package_test.py run-package-test ${{ matrix.image-type}}_x86_64
          python3 tests/package_tests/run_package_test.py run-package-test ${{ matrix.image-type}}_arm64

      - name: Run docker smoke tests
        if: startsWith( matrix.image-type, 'docker-')
        env:
          SCALYR_API_KEY: ${{ secrets.SCALYR_PROD_CLOUDTECH_TESTING_WRITE_TOKEN }}
        run: |
          source ./.circleci/smoketest_docker.sh scalyr/scalyr-agent-ci-unittest:4 json 150


  publish:
    needs: ["test"]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-type: [docker-json]


    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Push image from master branch.
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          python3 build_package_new.py ${{ matrix.image-type }} \
            --push \
            --registry \
            localhost:5000

      - name: Push image using master branch commit hash.
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          python3 build_package_new.py ${{ matrix.image-type }} \
            --push \
            --registry \
            localhost:5000



