apiVersion: batch/v1
kind: Job
metadata:
  name: agent-k8s-codespeed
  namespace: agent-benchmark
spec:
  template:
    spec:
      # capture script needs access to agent process to request its status.
      shareProcessNamespace: true
      restartPolicy: OnFailure
      containers:
        - name: metric-capture
          image: 137797084791.dkr.ecr.us-east-1.amazonaws.com/agent-benchmark/metrics-capture:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "100Mi"
            requests:
              memory: "100Mi"
          volumeMounts:
            - mountPath: /agent-data
              name: agent-data
            - mountPath: /backup
              name: captured-metrics-backup
          command: ["/bin/sh", "-c"]
          args: ["benchmarks/scripts/start-capture-metrics.sh ${COMMIT_SHA1}; benchmarks/scripts/send-log-level-counts-to-codespeed.sh ${COMMIT_SHA1}"]
          env:
            - name: CAPTURE_TIME
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config
                  key: capture_time
            - name: CAPTURE_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config
                  key: capture_interval
            - name: CODESPEED_AUTH
              valueFrom:
                secretKeyRef:
                  name: benchmark-secret
                  key: CODESPEED_AUTH
            - name: CODESPEED_URL
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config
                  key: codespeed_url
            - name: CODESPEED_PROJECT
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config
                  key: codespeed_project
            - name: CODESPEED_EXECUTABLE
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config-agent-settings
                  key: codespeed_executable
            - name: CODESPEED_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config
                  key: codespeed_environment
            - name: CODESPEED_BRANCH
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config
                  key: branch
            - name: COMMIT_DATE
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config-version
                  key: commit_date
            - name: COMMIT_SHA1
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config-version
                  key: commit_sha1
            - name: AGENT_DATA_PATH
              value: /agent-data
            - name: ADDITIONAL_CAPTURE_SCRIPT_FLAGS
              value: --metrics-backup-path=/backup
        - name: agent
          image: agent
          imagePullPolicy: Always
          resources:
            limits:
              memory: "100Mi"
            requests:
              memory: "100Mi"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: agent-data
              mountPath: /root/scalyr-agent-dev
          env:
            - name: SCALYR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: benchmark-secret
                  key: SCALYR_API_KEY
            - name: SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config
                  key: server_host
            - name: AGENT_GIT_URL
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config
                  key: agent_git_url
            - name: COMMIT_SHA1
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config-version
                  key: commit_sha1
            - name: SCALYR_SERVER
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config
                  key: scalyr_server
            - name: BRANCH
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config
                  key: branch
        - name: log-writer
          image: 137797084791.dkr.ecr.us-east-1.amazonaws.com/agent-benchmark/log-writer:latest
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args: ["benchmarks/scripts//write-log-lines.sh"]
          resources:
            limits:
              memory: "100Mi"
            requests:
              memory: "100Mi"
          volumeMounts:
            - name: agent-data
              mountPath: /agent-data
            - name: log-writer-data
              mountPath: /log-writter-data
          env:
            - name: LOG_WRITER_ADDITIONAL_ARGS
              valueFrom:
                configMapKeyRef:
                  name: codespeed-config-agent-settings
                  key: LOG_WRITER_ADDITIONAL_ARGS
            - name: AGENT_DATA_PATH
              value: /agent-data

      volumes:
        - name: config
          configMap:
            name: codespeed-config-agent-settings
            items:
              - key: agent-config.json
                path: config.json
        - name: agent-data
          emptyDir: {}
        - name: captured-metrics-backup
          emptyDir: {}
        - name: log-writer-data
          emptyDir: {}



